sudo: required

services:
  - docker

arch:
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
  - "sudo mkdir /run/shm"
  script:
  - "sudo /build/build.sh -v"
  
script:
- "travis_wait 30 sleep 1800 &"
- "sudo bash arch-travis.sh"
- "ls"

before_deploy:
  - sudo mv out/*.iso .
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

deploy:
  - provider: releases
    skip_cleanup: true
    draft: true
    api_key:
      secure: "BPRBpa0GJ0d5LFvqAoNB2gFm7BQwyUoKVaEdzl73xte4EGBWW5MNq975rlDezOa2LHNmfWXsVOFxXog2Z2tNqT+noheluEkx+ZatF1gtHqJmFo3vZSRwCLp8ZFVLaUuM00Oc8obptkJOtHVbVdUe7HqvsBqbYaLG/W3Bo1alFClkDZOiCbBEsmgmXueyNJXxo4Y5WWo/WfWZIHIObTj7ttAFYqLQppHSoXLiX3/WhGjQCFEensAnznb72v4Inofl4fORxBdMylacD8xHeQijNHtBk7XPIFChMRs1MbDf4c55fWR1jj1amQA3tbMaL+as0zDH3QwtFOR39Lo0hIkKRxv6kd9P8iw5bD1XQ0OiAz2wGzLkVavqjSv7/z3OiOtezFDtbpoNsPRbt7kxGtZwESMYEd8sM8d2SGQA21+NgWUH5wZPhL2HgY1AaHKfDBjhXEocCdZEcFf/esbzjXvcNjfPzWhSCeflVuSbdFZQMTR7gdFYY2RNmCexqd7mhmSY3pmDuZkfbve5oM4J3GMAMOuXV63SLjuW8Kh5noYBJeWFJWXzTn5P1yrMC1iW4PdxFBRNP87mok8qeYisghgA93hzWy0SX89cKr/yRK35wQYeomnCMp9M0Gu3Ljj1BIhgkN0LRDx2A9oYQIrkvdiXKIbUEcz8KImo1c9Ao7ML6tI="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: 
     - "/home/travis/${image_name}" #for future we can have multiple files so doing like this
    on:
      all_branches: true
